[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Michael Gebis <mike.gebis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
termion = "1.5.6"
itertools = "0.10.3"
num = "0.4.0"
